#!/bin/bash
# RSP 2010-09-16
echo
echo "Getnode - Copyright (c) 2010, 2011 Rafal Pocztarski"
echo "This program comes with ABSOLUTELY NO WARRANTY."
echo "You may redistribute it under certain conditions."
echo "See LICENSE for details."
echo
echo "Getnode downloads, configures, builds and tests node."
echo "Project home page: http://github.com/rsp/getnode"
echo
if [ "$1" == "" ]; then
    echo "Usage: getnode VERSION"
    echo "       getnode VERSION PREFIX"
    echo
    echo "Downloads: http://nodejs.org/dist/node-vVERSION.tar.gz"
    echo "and builds for installation in PREFIX or /opt/node by default."
    echo "If PREFIX is 'v' or 'V' it is equivalent to /opt/node-VERSION"
    echo
    echo "Examples: getnode 0.2.6"
    echo "          getnode 0.2.6 v"
    echo "          getnode 0.2.6 /usr/local"
    echo
    exit 1
fi
function error {
    echo -e "$1\n"
    exit 2
}
version="$1"
dir="node-v$version"
file="$dir.tar.gz"
url="http://nodejs.org/dist/$file"
if [ "$2" == "" ]; then
    prefix="/opt/node"
elif [ "$2" == "v" ] || [ "$2" == "V" ]; then
    prefix="/opt/node-$version"
else
    prefix="$2"
fi
echo "Getnode is going to download:"
echo "    $url"
echo "and build it for installation in:"
echo "    $prefix"

d1=`date '+%Y-%m-%d %H:%M:%S'`
if [ -d $dir ]; then
    error "Directory $dir already exists - remove manually"
fi
if [ -f $file ]; then
    echo "File $file already exists - skipping download"
else
    wget $url
fi
if [ ! -f $file ]; then
    error "File $file not found - download failed"
fi
tar xzvf $file || error "Error extracting $file"
if [ ! -d $dir ]; then
    error "Directory $dir not found - extraction failed"
fi
cd $dir
./configure --prefix=$prefix \
&& make && make test && echo DONE || error ERROR
d2=`date '+%Y-%m-%d %H:%M:%S'`
echo -e "From:\t$d1\nTo:\t$d2"
echo
echo "You can now run 'make install' or 'sudo make install'"
echo "to install $dir in $prefix"
echo

